version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python3 app/run.py
    volumes:
      - .:/app  # Mount current directory to /app in container
    environment:
      FLASK_ENV: ${FLASK_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      PYTHONPATH: /app  # Set the PYTHONPATH to /app inside the container
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
